/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GenomeBrowser;

import java.util.List;
import java.util.Map;

/**
 *
 * @author davidoluwasusi
 */
public class Visualizer extends javax.swing.JPanel {

    /**
     * Initializes the visualization with the given data.
     *
     * @param geneName The name of the gene to visualize.
     * @param exonData The exon data (map of gene names to exon positions).
     * @param geneStart The start position of the gene.
     * @param geneEnd The end position of the gene.
     */
    public void setGeneVisualization(String geneName, Map<String, List<int[]>> exonData, int geneStart, int geneEnd) {
        System.out.println("Setting visualization for gene: " + geneName);

        // Update instance variables
        // Clear the existing visualization
        visPane.removeAll();

        // Create the custom visualizer component
        GeneVisualizer visualizer = new GeneVisualizer(geneName, exonData, geneStart, geneEnd);
        visualizer.setSize(visPane.getWidth(), visPane.getHeight());
        visualizer.setVisible(true);

        // Add the visualizer to the panel
        visPane.add(visualizer);
        visPane.revalidate();
        visPane.repaint();
    }

    /**
     * Creates new form Visualizer
     */
    public Visualizer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visPane = new javax.swing.JPanel();

        javax.swing.GroupLayout visPaneLayout = new javax.swing.GroupLayout(visPane);
        visPane.setLayout(visPaneLayout);
        visPaneLayout.setHorizontalGroup(
            visPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        visPaneLayout.setVerticalGroup(
            visPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel visPane;
    // End of variables declaration//GEN-END:variables
}
